#!/bin/bash

#SBATCH --ntasks=512
#SBATCH --nodes=8
# SBATCH --mem=378240
#SBATCH --partition=amd
#SBATCH --job-name=animate
#SBATCH --time=01:00:00
#SBATCH --output=DMD-RA.out
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
# module load openmpi/4.0.5/amd
module load conda
source activate an

python src/DMD-RA-stationary.py
