#!/bin/bash

#SBATCH --ntasks=64
#SBATCH --nodes=1
#SBATCH --partition=amd
#SBATCH --job-name=interactive
#SBATCH --time=14:00:00
#SBATCH --output=INT.out
#SBATCH --exclusive
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
# module load openmpi/4.0.5/amd
module load conda
source activate an

sleep 72000
