#!/bin/bash

#SBATCH --ntasks=64
#SBATCH --nodes=1
#SBATCH --partition=highmem
#SBATCH --job-name=DMD
#SBATCH --time=8:00:00
#SBATCH --output=INT.out
# SBATCH --exclusive
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load texlive
# module load openmpi/4.0.5/amd
module load conda
source activate an
# module load openmpi/4.1.4/gcc

# pyton src/full-RA-stationary.py
sleep 720000
