#!/bin/bash
#SBATCH --ntasks=64
#SBATCH --nodes=1
# SBATCH --mem=243200
#SBATCH --partition=amd
#SBATCH --job-name=DMD
#SBATCH --time=5:00:00
#SBATCH --output=INTERACTIVE.out
# SBATCH --exclusive
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load texlive
# module load openmpi/4.0.5/amd
module load conda
source activate an
# module load openmpi/4.1.4/gcc

# python src/DMD-RA.py
sleep 720000
